#!/usr/bin/env python3
"""
Generate supabase/04_catalogue.sql from data/products.txt + data/groups.txt

    python3 src/gen_seed.py

The catalogue is the same source of truth the front end builds from, so the
database and index.html can never drift apart. Re-run this after
src/import_sheets.py and load the output into Supabase.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PRODUCTS = ROOT / "data" / "products.txt"
GROUPS = ROOT / "data" / "groups.txt"
OUT = ROOT / "supabase" / "04_catalogue.sql"

UNGROUPED = "Manual order"
# Groups placed by hand; the app only marks them as ordered.
MANUAL = {"Others", UNGROUPED}


def q(s):
    """Quote a SQL string literal."""
    return "'" + str(s).replace("'", "''") + "'"


def main() -> int:
    # ---- products ----
    products = []
    for raw in PRODUCTS.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        f = line.split("|")
        if len(f) < 2:
            print(f"skipping malformed row: {raw!r}", file=sys.stderr)
            continue
        code = f[0].strip()
        both = f[1]
        unit = (f[2].strip() if len(f) > 2 else "") or "kg"
        weight = (f[3].strip() if len(f) > 3 else "")
        margin = (f[4].strip() if len(f) > 4 else "")
        alias = (f[5].strip() if len(f) > 5 else "")

        # "English / Tamil" -> two columns
        if "/" in both:
            name, tamil = both.split("/", 1)
        else:
            name, tamil = both, ""

        products.append({
            "code": code,
            "name": name.strip(),
            "tamil": tamil.strip(),
            "unit": unit,
            "weight": weight,
            "margin": margin,
            "alias": alias,
        })

    # ---- groups ----
    groups, mapping = [], {}
    for raw in GROUPS.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        gname, _, codes = line.partition("|")
        gname = gname.strip()
        groups.append(gname)
        for c in codes.split(","):
            c = c.strip()
            if c:
                mapping[c] = gname

    if UNGROUPED not in groups:
        groups.append(UNGROUPED)

    known = {p["code"] for p in products}
    # A product in no group tab falls into Manual order (docs/WORKFLOW.md)
    unmapped = sorted(known - set(mapping))
    for c in unmapped:
        mapping[c] = UNGROUPED
    # a group tab may name a code the catalogue does not have
    orphans = sorted(set(mapping) - known)

    # ---- emit ----
    L = []
    L.append("-- ============================================================")
    L.append("-- Velora Fresh — product catalogue")
    L.append("--")
    L.append("-- GENERATED by src/gen_seed.py from data/products.txt and")
    L.append("-- data/groups.txt. Do not edit by hand: re-run the generator.")
    L.append("--")
    L.append(f"-- {len(products)} products, {len(groups)} groups, "
             f"{len(unmapped)} falling into {UNGROUPED}")
    L.append("--")
    L.append("-- Safe to re-run: every insert upserts.")
    L.append("-- ============================================================")
    L.append("")

    L.append("-- ---------- vendor groups ----------")
    L.append("insert into vendor_groups (name, manual, sort_ord) values")
    rows = [f"  ({q(g)}, {str(g in MANUAL).lower()}, {i + 1})"
            for i, g in enumerate(groups)]
    L.append(",\n".join(rows))
    L.append("on conflict (name) do update set manual = excluded.manual,")
    L.append("                                 sort_ord = excluded.sort_ord;")
    L.append("")

    L.append("-- ---------- products ----------")
    L.append("insert into products (code, name, tamil, unit, unit_weight_kg, alias) values")
    rows = []
    for p in products:
        w = p["weight"] if p["weight"] else "null"
        rows.append(f"  ({q(p['code'])}, {q(p['name'])}, {q(p['tamil'])}, "
                    f"{q(p['unit'])}, {w}, {q(p['alias'])})")
    L.append(",\n".join(rows))
    L.append("on conflict (code) do update set name = excluded.name,")
    L.append("                                 tamil = excluded.tamil,")
    L.append("                                 unit = excluded.unit,")
    L.append("                                 unit_weight_kg = excluded.unit_weight_kg,")
    L.append("                                 alias = excluded.alias;")
    L.append("")

    L.append("-- ---------- product -> group ----------")
    L.append("insert into product_groups (product_code, group_name) values")
    rows = [f"  ({q(p['code'])}, {q(mapping[p['code']])})" for p in products]
    L.append(",\n".join(rows))
    L.append("on conflict (product_code) do update set group_name = excluded.group_name;")
    L.append("")

    if orphans:
        L.append(f"-- {len(orphans)} code(s) named in a group tab but not in the")
        L.append(f"-- product list, so not inserted: {', '.join(orphans)}")
        L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  products {len(products)}")
    print(f"  groups   {len(groups)}")
    print(f"  -> {UNGROUPED}: {len(unmapped)}")
    if orphans:
        print(f"  codes in a group but not in the catalogue: {', '.join(orphans)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
